-- MYSQL database

DROP DATABASE IF EXISTS DATABASES_INFO;

CREATE DATABASE DATABASES_INFO;
USE DATABASES_INFO;

CREATE TABLE DB_BY_HOST(
	DB_CODE INT PRIMARY KEY AUTO_INCREMENT,
    DB_NAME VARCHAR(50) NOT NULL,
    DB_TYPE VARCHAR(100) NOT NULL,
    WEB_DOMAIN VARCHAR(150) NOT NULL,
    DB_HOST VARCHAR(250) NOT NULL,
    DB_PORT INTEGER,
    DB_USER VARCHAR(250),
    DB_PASSWORD VARCHAR(250),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);